### ISSUE TITLE
Error parsing certificate - malformed certificate

### ISSUE THREAD

**Issue by natalijapesic** [scrtlabs/secret.js#139]
Running the integration tests for the mysimplecounter example and getting this error. 
Connecting to the pulsar-2 testnet with my wallet. Uploading the contract works, i get the contract hash and code back. But on init it fails with:
```
          ^
Error: Error parsing certificate - malformed certificate
    at extractAsn1Value (/Users/wiz/repos/natali/mysimplecounter/tests/node_modules/secretjs/src/encryption.ts:191:11)
    at extractConsensusIoPubkey (/Users/wiz/repos/natali/mysimplecounter/tests/node_modules/secretjs/src/encryption.ts:157:19)
    at EncryptionUtilsImpl.<anonymous> (/Users/wiz/repos/natali/mysimplecounter/tests/node_modules/secretjs/src/encryption.ts:84:30)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/wiz/repos/natali/mysimplecounter/tests/node_modules/secretjs/dist/encryption.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    ```

**Comment by assafmo** [comment]
Use secretjs@beta (v1.7) with current pulsar-2

**Comment by assafmo** [comment]
`secretjs@1.7.1-beta.3` should work, please confirm :blush:

**Comment by natalijapesic** [comment]
> `secretjs@1.7.1-beta.3` should work, please confirm 😊

it works, thank you <3
